### ISSUE TITLE
Access To Data For Training

### ISSUE THREAD

**Issue by azibit** [fengggli/corn-ear-detection#3]
Hi,
Thanks so much for this. I am also working on something similar and was wondering if I could get access to the training and test data used for this. I would deeply appreciate

**Comment by fengggli** [comment]
Hi @azibit ,I added instructions in here: 34fc042c0ea002c92e9626df5de2a2ddc1bae03f.

**Comment by azibit** [comment]
Deep appreciation for your prompt response. Thanks so much @fengggli
